"""
Writer Agent — Synthesizes research and analysis into comprehensive reports.
"""
from datetime import datetime
from typing import Any, Dict

from langchain.messages import HumanMessage, SystemMessage

from src.agents.base_agent import BaseAgent
from src.workflows.state import AgentState

SYSTEM_PROMPT = """You are a Writer Agent specializing in synthesizing complex information into clear, professional reports.

You will receive a task, research findings, and analytical insights. Your goal is to create a comprehensive, well-structured Markdown report.

Structure your report using this template:

# [Report Title]

**Generated by IntelliAgents** | {date} | Task: [brief task description]

---

## Executive Summary
[2-3 paragraph overview of findings and key conclusions]

## Background & Context
[relevant context and why this topic matters]

## Key Findings
[detailed findings organized logically, with subsections as needed]

## Analysis & Insights
[integrated analysis, trends, and patterns]

## Recommendations
[specific, actionable recommendations]

## Conclusion
[strong closing summary]

## References & Sources
[numbered list of all cited sources with URLs]

---
*Report generated by IntelliAgents Multi-Agent System*

Rules:
- Use clear, professional language
- Include all important data points from research and analysis
- Make recommendations specific and actionable
- Cite sources inline using [N] format referencing the numbered references section
- Aim for comprehensive coverage (800-1500 words)
"""


class WriterAgent(BaseAgent):
    """Synthesizes all agent outputs into a final professional report."""

    def __init__(self):
        super().__init__(name="Writer", temperature=0.4)

    def run(self, state: AgentState) -> Dict[str, Any]:
        task = state["task"]
        research_data = state.get("research_data", "")
        analysis = state.get("analysis", "")
        critique = state.get("critique", {})
        iteration = state.get("iteration", 0)
        subtasks = state.get("subtasks", [])

        writing_desc = next(
            (s["description"] for s in subtasks if s.get("agent") == "writer"),
            "Write a comprehensive report synthesizing the research and analysis.",
        )

        if iteration == 0:
            state = self.log_entry(state, "Received analysis data. Beginning report synthesis.")
        else:
            feedback_summary = "; ".join(critique.get("feedback", [])[:2])
            state = self.log_entry(state, f"Revision #{iteration} — Addressing Critic feedback: {feedback_summary[:80]}")

        state = self.log_entry(state, "Drafting comprehensive report structure.")

        # Build revision context if this is a retry
        revision_context = ""
        if iteration > 0 and critique:
            feedback_items = "\n".join(f"- {f}" for f in critique.get("feedback", []))
            revision_context = f"\n\n**CRITIC FEEDBACK TO ADDRESS (Score was {critique.get('score', 'N/A')}/10):**\n{feedback_items}\n\nPlease improve the report addressing all the above points."

        messages = [
            SystemMessage(content=SYSTEM_PROMPT.format(date=datetime.now().strftime("%B %d, %Y"))),
            HumanMessage(
                content=(
                    f"Task: {task}\n\n"
                    f"Writing Goal: {writing_desc}\n\n"
                    f"Research Findings:\n{research_data}\n\n"
                    f"Analysis & Insights:\n{analysis}"
                    f"{revision_context}"
                )
            ),
        ]

        response = self.llm.invoke(messages)
        report = self._extract_text(response)

        state = self.log_entry(state, "Report draft complete. Sending to Critic for quality review.")

        return {
            **state,
            "report": report,
            "current_step": "critique",
        }
